name: CI

on:
  push:
    tags:
      - 'b*'

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: go.mod

      - name: Mod Tidy
        run: go mod tidy

      - name: Build
        run: ./script/build

      - name: Test
        run: go test ./...
